# Generated by Django 3.1 on 2020-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='timetable',
            field=models.CharField(max_length=2200),
        ),
    ]
